name: Report an issue with Home Assistant Registry
description: Report an issue with Home Assistant Registry
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Problem
      description: >-
        Describe the issue you are experiencing here, to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        # Environment
  - type: input
    validations:
      required: true
    attributes:
      label: Home Assistant Registry Version
      placeholder: e.g. v2.2.5
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    validations:
      required: true
    attributes:
      label: Debugging Information
      description: >-
        Include logs after enabling debugging.
